# Generated by Django 4.0.3 on 2022-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspek',
            name='kegiatan',
            field=models.ManyToManyField(blank=True, to='monitoring.kegiatan'),
        ),
    ]
