# Generated by Django 4.0.3 on 2022-03-10 10:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('kelas_Id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('kelas', models.CharField(db_index=True, max_length=5, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='NISN')),
                ('nama_Lengkap', models.CharField(db_index=True, max_length=50)),
                ('ttl', models.DateField(blank=True, verbose_name='TTL')),
                ('status_Santri', models.CharField(blank=True, choices=[('l', 'Putra'), ('p', 'Putri')], max_length=1)),
                ('alamat', models.CharField(help_text='Nama jalan, blok, desa, RT/RW atau kelurahan', max_length=100)),
                ('Kota', models.CharField(max_length=20)),
                ('provinsi', models.CharField(max_length=20)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('telp_Wali', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Isi dengan nomer telfon orang tua wali <em>(e.g. +621334064094)</em>.', max_length=128, region=None)),
                ('tinggi_Badan', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Tinggi badan (CM)')),
                ('berat_Badan', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Berat badan (KG)')),
                ('golongan_Darah', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'AB'), ('4', 'O')], max_length=1)),
                ('riwayat_Penyakit', models.CharField(blank=True, max_length=100)),
                ('nama_ortu', models.CharField(blank=True, max_length=50, verbose_name='Nama Orang Tua')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosantri/')),
                ('alamat_Lengkap', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='master_data.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_Guru', models.CharField(blank=True, choices=[('u', 'Ust. '), ('h', 'Usth. ')], max_length=1)),
                ('nama_Lengkap', models.CharField(db_index=True, max_length=50)),
                ('ttl', models.DateField(blank=True, verbose_name='TTL')),
                ('alamat', models.CharField(help_text='Nama jalan, blok, desa, RT/RW atau kelurahan', max_length=100)),
                ('Kota', models.CharField(max_length=20)),
                ('provinsi', models.CharField(max_length=20)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('nomer_Telpon', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Nomer telpon <em>(e.g. +621334064094)</em>.', max_length=128, region=None)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosantri/')),
                ('alamat_Lengkap', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas_Diampu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='master_data.kelas')),
            ],
        ),
    ]
