# Generated by Django 4.0.3 on 2022-03-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='berat_Badan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Berat badan (KG)'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='tinggi_Badan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tinggi badan (CM)'),
        ),
    ]
