# Generated by Django 4.0.3 on 2022-03-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_santri_berat_badan_alter_santri_tinggi_badan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'verbose_name_plural': 'Data Guru'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name_plural': 'Data Kelas'},
        ),
        migrations.AlterModelOptions(
            name='santri',
            options={'verbose_name_plural': 'Data Santri'},
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='slug',
        ),
    ]
