# Generated by Django 4.0.3 on 2022-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_rename_kota_guru_kota_rename_kota_santri_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='title_Guru',
            field=models.CharField(blank=True, choices=[('u', 'Ust. '), ('h', 'Usth. ')], max_length=5),
        ),
    ]
