# Generated by Django 4.0.3 on 2022-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_alter_guru_title_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='title_Guru',
            field=models.CharField(blank=True, choices=[('u', 'Ust.'), ('h', 'Usth.')], max_length=1),
        ),
        migrations.AlterField(
            model_name='guru',
            name='ttl',
            field=models.DateTimeField(blank=True, verbose_name='TTL'),
        ),
    ]
